### ISSUE TITLE
How to use directive only in browser.

### ISSUE THREAD

**Issue by consigliory** [MarkPieszak/aspnetcore-angular2-universal#103]
I need to use ng2-dragula and it seem to have same ReferenceError: document is not defined issue.
It looks like I can add DragulaModule only for app.browser.module.ts but I still need to have [dragula]='"third-bag"' in template. and angular complains that [dragula]='"third-bag"' is not known property. Do I need to somehow create different template for serverside rendering? I tried to set ngIf so it is rendered optionally without luck. Could you please suggest what I need to do in this cases?

**Comment by MarkPieszak** [comment]
So in order to make things like that easier I'm going to do a little refactoring to the `app.module` & `app.browser.module | app.server.module`.

Let me look over PR #102 (which moves the directory structure around to follow a more .NET standard) and then I can add these in there.

I'll merge over these app.module changes and leave an example of this so future people can benefit from it as well!

But the jist is... (you can see in the dep injection branch here https://github.com/MarkPieszak/aspnetcore-angular2-universal/compare/dep-injection)

You can see I pulled everything -out- from the NgModule in app.module, and made them all exportable `COMMON_IMPORTS | COMMON_COMPONENTS` etc. Then I just add those into each app.platform module. Adding ng2-dragula Module to only App.browser.module (now it's the Root), everything works like a charm :+1: :100:
