### ISSUE TITLE
VS2017

### ISSUE THREAD

**Issue by jrmcdona** [MarkPieszak/aspnetcore-angular2-universal#118]
Hi Mark,
This looks great.  I am using the  JavaScriptServices VS template and have it running to in VS2017 and the team is using that.

Will this starter pack simply fail in VS2017 or convert fine?   Thinking about upgrading to this starter pack because I want webpack2 and karma up and running.   

Thanks

**Comment by MarkPieszak** [comment]
We finally just merged in some of the big structural changes to the Repo, if someone wants to take a look, it's definitely time to upgrade now that VS2017 is coming out around the corner!

We have the one solution file at the `root`
and the one project.json file in `AspCoreServer`

PRs always welcome of course if you want to look at JavaScriptServices for reference on how to upgrade them!

I'm unfortunately gone tomorrow through Friday otherwise I could get it in there :(

**Comment by albrookesplowman** [comment]
Now that I have VS2017 Enterprise installed, do you want me to have a look at building it in VS2017?

**Comment by MarkPieszak** [comment]
Hey @albrookesplowman it's ok I'm actually doing several things at the same time to get the repo up to date: angular4, platform-server, AoT, vs2017, and a few others. 
Shooting to have them in the repo by tomorrow.
It will still be rc anfular4, but thought it'd be nice to have people test it out a little bit on their end so we can give some feedback.

So far last remaining bug is that animations error on the server but it's in the works!

**Comment by pjmagee** [comment]
I actually used the template you provided but we have since moved forward on our project and have successfully migrated to VS2017. Just double check the launchSettings.json file that is used by Visual Studio. But the migration from project.json to project.csproj was handled by Visual Studio perfectly fine.

**Comment by MarkPieszak** [comment]
4.0 branch [here](https://github.com/MarkPieszak/aspnetcore-angular2-universal/tree/angular4.0-NEW-wip), uses VS2017. Will have it all in Master once it's more up to date with the Master repro.

**Comment by MarkPieszak** [comment]
I merged into Master, so we're on 2017 only now :+1: :100: 

Fixing any issues and upgrading a few things today
