### ISSUE TITLE
[Feature Request] IntelliSense with Resharper

### ISSUE THREAD

**Issue by StefanRein** [MarkPieszak/aspnetcore-angular2-universal#125]
Hey,

using TypeScript 2.2 and Resharper (Build 2017.1 EAP 3 - Released February 28, 2017)
https://www.jetbrains.com/resharper/eap/

He can not resolve all the `export * from 'folder'`, like `export * from 'app'`. He does not know to search in the index.ts file and get everything from there. 

Maybe you could look into that?

**Comment by MarkPieszak** [comment]
So until we get the upgade to Angular 4.0 you actually can't go above TypeScript 2.0.10 (higher versions of TS do more advanced type inference which breaks Angular, but these things are fixed in 4.0+)

That might be part of the issue, when we upgrade to 4.0 let's re-look into this and hopefully it'll all work then!

**Comment by MarkPieszak** [comment]
So now that we're above TS 2.2+ can you take another look?

I'll close it out but let me know if we need to revisit it! Thanks :+1:
