### ISSUE TITLE
Server side requires absolute url for http request?

### ISSUE THREAD

**Issue by pjmagee** [MarkPieszak/aspnetcore-angular2-universal#146]
This isn't particularly an issue with the template, but since I see you are working with the Nodejs and JavascriptServices side for the ASPNET prerendering, i figured i'd ask the question here. What is the best way to get a full current domain so i can prefix it to existing api calls that are relative?

**Comment by MarkPieszak** [comment]
I was actually adding that into the project just earlier didn't get a chance to commit it just yet.
There are multiple ways though, but basically from either the boot-server, we can pass in the APP_BASE_HREF, or another Service we use for Http, there's many options like that. But we can pass params.origin into that and utilize it. 

I'm on an iPad but I'll try to get the PR in so you can see what I mean!

To answer the question though yes we need them now. Previously we were "assuming" if you didn't provide a full URL we could use the originUrl from Node, but they didn't want to continue that habit.

HttpInterceptors are coming in 4.1, which will make this even easier since we'll be able to just prepend any http urls with what we want on the server.

Hope that makes sense!

**Comment by pjmagee** [comment]
That would be great! I'm currently in the process of migrating to Angular4 and we were heavily relying on the original template this repo provided. But I've been keeping an eye on this repo and making changes accordingly.  👍  Thanks for all the work thus far, it's been really helpful.

**Comment by MarkPieszak** [comment]
Glad to help! I know it's been changing a lot, think it got more confusing than helpful after a bit, wanted to keep it at least a little simpler this time around.

It's already confusing enough sometimes right :) haha

**Comment by MarkPieszak** [comment]
Done via #151 

It's passed down into APP_BASE_HREF through the server (params.origin).

Check out the Rest demo (/users) for an example useage :+1:
