### ISSUE TITLE
The program "[6536] dotnet.exe" exited with code -2147450749 - vs2017

### ISSUE THREAD

**Issue by novopashinmm** [MarkPieszak/aspnetcore-angular2-universal#162]
I open project in vs2017. Press F5. Wait while download all and then I get message
"The program "[6536] dotnet.exe" exited with code -2147450749 (0x80008083)"
What I can do? Please, help.

**Comment by novopashinmm** [comment]
![image](https://cloud.githubusercontent.com/assets/7537491/24805550/d8bf63cc-1bba-11e7-9128-e20948235b9b.png)

**Comment by MarkPieszak** [comment]
Do you have the latest version of VS2017 and everything?

**Comment by MarkPieszak** [comment]
Check this comment as well:

> Ok, I got it working. I think what was happening was that the x86 path for dotnet was being used and I had old versions of dotnet installed there. To fix this I went through and ran uninstall against every dotnet sdk/runtime installer I downloaded (no easier way?) then reinstalled the newest x64 sdk and runtime. I saw that the path of dotnet changed from x86 to x64 after I did this (see get-command dotnet). When I run dotnet --info it now says version 1.0.1. I think installing the latest x86 binaries would have worked too.

Might have to uninstall older versions of dotnet sdk if you have them

**Comment by Ketrex** [comment]
Adding a global.json file to the root of the project will fix this and ensure the correct SDK is used every time. dotnet core is designed to allow for multiple runtimes and SDKs to run side-by-side.

Without global.json, it will utilize the default CLI referenced SDK.

@MarkPieszak , want a PR for this?

**Comment by MarkPieszak** [comment]
Sure if you can Ketrex! I thought there was a global file, interesting.
https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/global.json

Is it something different than that file?

**Comment by Ketrex** [comment]
@MarkPieszak, whoops, should have taken a closer look, not sure how I overlooked the fact that it's already there.

The SDK version specified in the current global.json is 1.0.0, the latest version of the SDK is 1.0.1. I'm not sure which one you intend to target.

I suspect the problem was that they had an earlier, beta version of the SDK and not the actual 1.0.0 release. dotnet core will fallback to the default CLI version (and in this case fail) if the specified version in global does not exist.

Users shouldn't have to uninstall previous versions, they just need to make sure they have the intended target version installed. It would be nice if MS had provided a CLI utility to list all the installed version.

**Comment by MarkPieszak** [comment]
Yeah they definitely shouldn't have to, just figured play it safe and remove them all just incase 😆 

Closing this one out, hope you got it working @novopashinmm !
