### ISSUE TITLE
Thoughts on implementing AuthGuard on pre-rendered apps?

### ISSUE THREAD

**Issue by dguisinger** [MarkPieszak/aspnetcore-angular2-universal#181]
Hey Mark,
I know you've been working on passing state back to the browser.  Any thoughts on applications that have authentication needs?

I'm looking at the scenario of where the server-side doesn't know the user is authenticated on pre-render and an AuthGuard kicks them to a login page.

**Comment by MarkPieszak** [comment]
How are you checking for tokens currently? 

One way you could do it, is use dependency injection to have different ways to check for Auth for browser/server, maybe have the browser check for a localstorage bearer token and the sever call a rest API to check for authorization.

You're right though, it'd be a good idea to implement this in the repo so people know how to handle it!

**Comment by dguisinger** [comment]
Thats a good question; for me I'm using Amazon Cognito... I've been thinking about asking a similar question on their side as they have an ng2 example if they've looked at server side rendering.  I don't know the details about how the internals of their library works for passing the token. 

I figure if there is a good reference design, its easier to figure out how to adapt a library into it.

**Comment by MarkPieszak** [comment]
In your case then you could take the token and use the transfer Cache to pass it down to the browser and you could reuse it there?

**Comment by dguisinger** [comment]
I'd have to play with Amazon's SDK some more to find out; I originally had to disable server side execution because of an exception - but maybe if I look into it more I can figure it out.  The problem with 3rd party libraries is many aren't designed with server side execution in mind.

**Comment by LunicLynx** [comment]
This is exactly what i'm trying to figure out.

My current idea, is using a hybrid strategy. 
For SSR an Auth cookie should suffice. It should not be to hard to delegate the identity to server side called Api's.
Api calls should use localstorage bearer token.

If i get it working i open a PR.

**Comment by kyse** [comment]
How would you handle change in state? So I setup something similar, accessing isAuthenticated from the home controller and sending it to the spa via transferData, I have the auth service check the value on initialization.  Then during login or logout, update an internal isAuthenticated bool in the auth service.  The thing I notice when I add an auth guard to the default route to redirect to accounts/login, on initial page load, logging in, redirect to default route, I notice a refresh of the browser shows the login page briefly until the app finish loading up then presents the default route component as it should since I'm already logged in with an existing cookie.  Need to find a way to fix the brief appearance of the login page on reload when a user has refreshed the page or perhaps when they have an cookie that is set to be persistent.

**Comment by isaac2004** [comment]
@kyse kinda hacky, but you could hide the page in an *ngIf based on some value in your service. That way you only show the login page if you truly need to be there

**Comment by isaac2004** [comment]
@LunicLynx ever get an example working?

**Comment by isaac2004** [comment]
I have created a branch that shows end to end JWT flow. Please take a look and let me know if it satisfies your needs
