### ISSUE TITLE
How to setup routes for API so it return 404 if route not found.

### ISSUE THREAD

**Issue by skorunka** [MarkPieszak/aspnetcore-angular2-universal#214]
Is it possible and how to setup routes to API controllers, so that the Action was not found 404 is returned instead of "home/index"?

**Comment by MarkPieszak** [comment]
You're saying you don't want Angular to handle 404s but for .NET to do it?
I believe you could either make the Routes in StartUp more specific (haven't tried it personally), and map exactly what your front-end & back-end routes all are, otherwise 404. (This is what Node does in an angular universal scenario).

Or you're going to have to just create some type of TypeScript service where you can simply flag a boolean to true when Angular 404's, then pluck that service in main.server, pass it back to .NET during the serialization process, and do a `Redirect` instead of `return View();`

Hopefully that made sense? It's a lot of ping pong basically :)

**Comment by isaac2004** [comment]
@skorunka do you have any concerns with this being closed?
