### ISSUE TITLE
"Property 'users' is private" error when publish to Azure

### ISSUE THREAD

**Issue by Deitro** [MarkPieszak/aspnetcore-angular2-universal#216]
It was my first time publishing to Azure, so I can be wrong. I created **AppService** in Azure and in VS 2017 select **Publish** from menu. 
It finished with error: "Property 'users' is private and only accessible within class 'UsersComponent'".
Then I went to _users.component.ts_ and change **private**
```
private users: IUser[];
private selectedUser: IUser;
```
to **public**... And publish was succeeded.

**Comment by MarkPieszak** [comment]
Yes, so you can't have `private` `properties` or `methods` used within a Template, otherwise the AoT compiler throws errors since it wasn't able to properly statically analyze them.

You can test your code to see if you have any AoT errors by doing `npm run build:aot` at anytime, just to make sure everything is working properly.
