### ISSUE TITLE
This template is very slow at compilation

### ISSUE THREAD

**Issue by fmj02** [MarkPieszak/aspnetcore-angular2-universal#217]
This template is 100 times slower than the one generated with yeoman with Angular2. It takes like 30 seconds to build(and sometimes I even get a timeout) while the template generated with aspnetcore-spa takes only 1-2 seconds.

**Comment by MarkPieszak** [comment]
The very slow loading / building is definitely from the first-time load.
If you're opening it in VS2017 let's say for the first time and hitting F5, it takes quite a while for that first webpack run to happen. When downloading with the yeoman generator, it actually runs the webpack vendor & webpack configs automatically. These are things I'll definitely add back in here, for now the webpack configuration is fairly basic, it needs a few improvements no doubt!

The timeout or error can happen because during that same load it hasn't finished compiling yet.
Usually this build process is quicker on further project startups (F5 etc)

Another thing is that on the first (sometimes second run) in *development* mode, it's actually compiling your app & NgModule from JIT into an AoT ngModuleFactory, so this can take a few seconds as well. You'll notice after words it speeds up tremendously since this then gets *cached*. The Server rendering only handles AoT, that's why it's doing this.

There's no doubt some improvements that can and will be made, I'm just moving this week so it'll be tough to get them all in, but they'll be in there and we'll be much faster soon enough!

I'll definitely get some sort of auto webpack builds in with a yeoman template or dotnet template once I publish there (when everything is more polished).

As always PRs are appreciated with any improvements :)

**Comment by TimHarker** [comment]
This is my experience also (very slow) - and I haven't had a chance to look at it as I'm trying to create an application with it :-).

![image](https://cloud.githubusercontent.com/assets/5775607/25386972/22e6b3b2-2997-11e7-95a8-1f63bf1de390.png)

**Comment by yanbu0** [comment]
I am also seeing excessively long webpack builds and hot updates don't seem to work for the most part.  Getting the same errors as @TimHarker.  Also, I seem to get multiple webpack rebuilds when I make changes?

**Comment by MarkPieszak** [comment]
I'll try to tackle this one tomorrow, moving this week. Should of fixed it in the first place sorry guys!

**Comment by JohnGalt1717** [comment]
I'm also getting brutally slow AOT compiles (i.e. like 16-20 minute compile times!
