### ISSUE TITLE
Get "ERROR in No template specified for component <ComponentName>" for AOT build.

### ISSUE THREAD

**Issue by skorunka** [MarkPieszak/aspnetcore-angular2-universal#232]
Got the above error for any Component in my project while running: 
`webpack --env.aot --env.client`

sample component:
```
@Component({
	selector: "eyc-time-control",
	template: require("./timeControl.component.html")
})
```

The html file exists and in dev mode(just executing `webpack`) all works.

If I move the template content inside the `@Component.template` like `"template": "<div></div>"` or use `"templateUrl: "./timeControl.component.html"`, the error is gone.

Any idea?

**Comment by MarkPieszak** [comment]
So basically `@ngtools/webpack`, which is what we're using to build production mode, I'd imagine it's not triggering that `require()` since it's expecting a *string* there, and when it sees `templateUrl` it automatically  wraps it in a `require( )` (you can notice a similar error if you use `templateUrl: require()`, since it'll end up doing a double-require.

Strange behavior I know, but it's just something finicky with ngtools so not your fault! 
I hope that makes more sense though?

**Comment by skorunka** [comment]
Hi, so I suppose we should not use `template: require(".")` as it wont compile for production. Thank you.

**Comment by MarkPieszak** [comment]
Yes that'll do it! Strange but maybe ngtools will improve soon to know there's a require already so not to add another one in there.

**Comment by lixaotec** [comment]
Does it works now?

I´ve been struglling to get template concatenation working with AoT.

import temA from './temA.html'
import temB from './temB.html'

...
@Component..
template: (temA + temB) as string,
...

It works on dev with webpack using raw-loader
But building prod i get the error "ERROR in No template specified for component"

Apreciate any help
