### ISSUE TITLE
Connecting to a SQL DB

### ISSUE THREAD

**Issue by jtcoyle** [MarkPieszak/aspnetcore-angular2-universal#233]
Mark,

I am new to Angular and I was wondering if you could provide an example how to connect to a SQL DB to maintain the users list?

Joe

**Comment by MarkPieszak** [comment]
Hey Joe, you can see [here in this repo](https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Startup.cs#L53-L57) we're connecting to a SQLite code-first database so it's actually fairly similar. 

Check out this article it'll help get you setup with an existing SQL Database:
https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db

If you poke around the `/Server/` folder you'll see how we're doing some of the SQLLite stuff.

Luckily there's nothing different on the Angular you need to do, it's basically all setup within the `Startup.cs` file where you're setting your connection strings etc. 
Also, you can connect to an Azure database fairly similarly as well! 💯 

I hope that helps if you get it working post a little `gist` on here I'm sure others would love to know how to set it up! We could also add a nice README for it. 👍

**Comment by kyse** [comment]
Some config has changed form the main repo, but you get the point:

Startup.cs - ConfigureServices():
```
//services.AddEntityFrameworkSqlServer().AddDbContext<DbEntities>();
services.AddEntityFrameworkSqlite().AddDbContext<DbEntities>();
```

DbEntities - OnConfiguring():
```
optionsBuilder.UseSqlite(_connectionString);
//optionsBuilder.UseSqlServer(_connectionString);
```
And obviously in constructor you need to store connection string.  I inject a config service to grab folder paths (based on env, win or linux) to store DB in user config folders.  Not needed if you're using SQL Server since your server will most likely be on another machine in prod, so just feed it your connection string in Startup.cs like the original repo does.

**Comment by jtcoyle** [comment]
Thank you both.  I will take a look at this in a few days when I have time.  I am looking forward to getting this to work.
