### ISSUE TITLE
Differences between npm run build: dev and webpack --progress --color

### ISSUE THREAD

**Issue by cristiancamiloperezlopez** [MarkPieszak/aspnetcore-angular2-universal#264]
Hello,
I would like to know the difference between executing the following commands:

`npm run build:dev`
`webpack --progress --color`

I have already made different changes in the template and it is strange that if I run npm run build: dev errors are presented, but if I run webpack --progress --color everything compiles correctly

Oh and another thing, do you know how to interpret npm-debug.log?
Because I always seem to write a generic error message and I do not find clues about my error ...

Thank you very much

**Comment by MarkPieszak** [comment]
If you're running webpack in your command line, it's because you have it installed globally and it could be some older version that doesn't understand the config and such properly so it thinks everything is ok. The repo comes with webpack as a dependency so anything ran via scripts through npm/yarn comes from the ./node_modules locally.  Hope that helps explain it a little more!

Anything else feel free to ask! I'll close this one out for now.

**Comment by cristiancamiloperezlopez** [comment]
Hi Mark !!
You are right, thank you so much.
