### ISSUE TITLE
Server side translation

### ISSUE THREAD

**Issue by kyse** [MarkPieszak/aspnetcore-angular2-universal#291]
So I kept noticing when I added translation various places, I'd get the translation key showing up when i refresh the page until the translationhttploader gets a chance to call thee json file.

I did a test and created an api endpoint to return the json then switched the translation http loader to use the api endpoint.

I notice when I load up the site, and refresh, the server side rendering properly translates the page correctly (at least using the default english translation), and even though there's a very brief flash in the browser when the httploader gets a chance to call out to the API on the browser side, all the values are proper.  No more translate keys showing up before hand.

I suspect there's something going on server side rendering wise causing the static file parsing to fail.  Also, once fixed, having the http loader call up the translations when it's already using english is pointless.  Probably be good to add a check there somehow.

Finally.. I was reading around and noticed server side rendering with proper translation is tough to do because you end up with a ton of different bundles, one for each language, then you have to figure out which version to serve up.  Just throwing that out there.

**Comment by MarkPieszak** [comment]
Yes unfortunately that part is very difficult we've talked about that a few times. You do have to create separate bundles and know which one (on the ASP.NET / Node / whatever) server-side to serve up, instead of just `main.js` you'd do `main.japan.js` etc.  It's not the easiest process without a doubt, we can't really have all of that preconfigured for everyone here since not everyone needs that kind of Translation in their apps, at least we have a good starting point for people setup!

But if that's something you'd need to do, yes, you need to read headers and analyze what language (on the .NET side in the HomeController, and serve that bundle).

Quite annoying, but there's no other way unfortunately!
