### ISSUE TITLE
Prerendering timed out after 30000ms because the boot function

### ISSUE THREAD

**Issue by wilrek** [MarkPieszak/aspnetcore-angular2-universal#323]
Prerendering timed out after 30000ms because the boot function

I have just used ngx-bootstrap:
 <carousel [interval]="myInterval" [noWrap]="noWrapSlides" [(activeSlide)]="activeSlideIndex">
      <slide *ngFor="let slide of slides; let index=index">
        <img [src]="slide.image">

        <div class="carousel-caption">
          <h4 [innerHtml]="slide.title"></h4>
          <p [innerHtml]="slide.excerpt"></p>
        </div>
      </slide>
    </carousel>

component.ts
call after webservice retrieved the data

**Comment by MarkPieszak** [comment]
So it's because the carousel is running an interval so the server never knows when to render. Try wrapping myInterval and such with isPlatformBrowser, you want to ignore this from rendering (or at least running any type of interval) on the server. You want the server to render asap.

Hope that helps!
