### ISSUE TITLE
Update instructions

### ISSUE THREAD

**Issue by Silverdark** [MarkPieszak/aspnetcore-angular2-universal#34]
Before I think of using this, I would like to know how I can maintain the newest updates from the repository.

Should I fork the repo and merge every time the updates of this repo to my repo or is there an other update mechanism I don't know about? If yes, you could add this to the readme :).

Thanks in advance.

**Comment by MarkPieszak** [comment]
Great idea! I'll have to write something up on that.
I'm going to make some bigger updates soon (now that the holidays are over and I have more time), and I'll try to keep a **CHANGELOG** going for bigger changes then on. 

*Ideally*, I'd like to have the project be a drop-in replacement, where you pull-down the latest, and simply replace the Client & Server folders from the new version you pulled down, (with your current ones). I would think this would work for changes that happen with the infrastructure of the App. Let's say new additions to webpack / build / testing configuration etc.

I'll need the Changelog so I can note other potentially important changes/updates I make, maybe ones that showcase newly added features to the Client app itself, etc. So that you can have an easier time differentiating between them.

But I'm glad you brought this up, I was actually thinking about this problem the other day :)
