### ISSUE TITLE
DevExpress and DevExtreme support

### ISSUE THREAD

**Issue by albrookesplowman** [MarkPieszak/aspnetcore-angular2-universal#345]
Hi Mark,

I don't know if you have heard of them but we use the DevExtreme client side controls from DevExpress.  However, they currently say that they do not support Server side rendering

https://js.devexpress.com/Documentation/Guide/VS_Integration/Add_DevExtreme_to_NET_Core_Angular_2_Template/

Therefore, I assume that the options that I currently have are:

1.  Do not include any of their controls on the first pages that get loaded as they will not work until the angular SPA kicks in.
2.  If necessary, I could use there server side ASP.NET MVC controls on the initial page and then switch to their DevExtreme version once the angular SPA kicks in.

Do these options make some sort of sense, and if so, what is the best way of configuring option 2?

Many thanks

Al

**Comment by isaac2004** [comment]
Is there a particular reason you are trying to use this template? This template is great for SSR/HMR/SEO, and you have dependencies that don't support it. There are tons of Angular Universal templates that are less complex than this one because they don't have those features. This template is hard to implement because of those features, so in my opinion if you can't use them, it's not worth the hassle.

**Comment by isaac2004** [comment]
@albrookesplowman closing this unless you have a particular example that is not working
