### ISSUE TITLE
Please expand on how WebPack works in the project.

### ISSUE THREAD

**Issue by Adondriel** [MarkPieszak/aspnetcore-angular2-universal#347]
I am struggling to understand, in general how WebPack works, and I am having issues with the file size of the compiled pack that is generated by the webpack, I'm getting a file size of 7.3MB and that is just, insane. 

I also want to simplify the project, and get rid of unneeded files, so I want to remove the SSR stuff, because as I've found out over time, there are projects out there that don't care about SSR so they use dom references, and that breaks SSR. I have removed it, the simply way, but I'de like to remove it completely. 

Like, in the Q&A section, for removing SSR, what is "boot-client", where is that set?

**Comment by MarkPieszak** [comment]
Mainly those larger sizes are only in development mode, which doesn't matter since it's all for debugging / HMR etc.

The project is going to align a little bit more with JavaScriptServices soon, and yes ideally some type of flag would be nice to remove SSR, but there are so many moving pieces it ends up being very difficult to manage / do, especially since it's the goal of this repo. 

It might be easiest to take a JavaScriptServices project, and remove SSR from that, since that app doesn't start off as complex (and push the limits of SSR that we have setup here). You remove an asp-prender tag from index.cshtml and you're all set.

**Comment by Adondriel** [comment]
ok, thanks. The 7.3MB is in production, for some reason no matter what I do, my file size never changes.

**Comment by Adondriel** [comment]
I think i'm just going to completely re-do the compiling in my project, tbh. I really don't need all this complex stuff, lol. Considering almost none of the frameworks available atm break SSR anyway.

**Comment by MarkPieszak** [comment]
That's very strange, some of them are for SSR, others are just for the general kitchen-sink the project provides atm.

Just take JSServices, and remove SSR, and it'll be easier at least!
SSR raises the barrier of entry quite a bit, you have to use dependency injection to make sure the server ignores things and only the client uses them, etc.

I'll close this out then, hope it goes well!
