### ISSUE TITLE
Swap out view bags to tag helper

### ISSUE THREAD

**Issue by mexanichp** [MarkPieszak/aspnetcore-angular2-universal#366]
Hello, I was looking at the HomeController inside angular2 branch and compare it with the master. 
For me seems unclear why for now there are a lot of complex logic instead of using just one tag helper?

**Comment by MarkPieszak** [comment]
Hey @mexanichp so it's mainly because here we need to manually control and get access to every part of the dotnet -> node -> angular and all way back to node then dotnet again. We are pulling out all the necessary SEO aspects that are important as well as passing data down to angular from dotnet.

When you use the taghelper itself you lose most of that.

If you know of someway to clean it up though, I'm all ears! 👍

**Comment by mexanichp** [comment]
@MarkPieszak thank you for the explanation. Unfortunately, I don't know how to achieve this without losing SEO things 👍

**Comment by MarkPieszak** [comment]
Glad to help! Look for updates as well, I'm in a massive rewrite now to try to re-align with the companion repo (JavaScriptServices) to help make it more extensible for those coming from there as well as clean and make a few things easier to do and understand.
