### ISSUE TITLE
Latest Clean Build - fails

### ISSUE THREAD

**Issue by OceansideBill** [MarkPieszak/aspnetcore-angular2-universal#434]
I'm running node v8.6 and npm 5.4.2.

Pulled a copy of the latest changes to my local machine.  
Immediately failed on npm install.
Reran npm rebuild node-sass - didn't help
Deleted my node_modules folder and did a fresh npm install.
This worked, for npm install.

npm run build:dev then failed.

Getting an errors TS2345 and TS2034.

I'm holding off updating my fork 
![build-dev](https://user-images.githubusercontent.com/13558268/31313772-9f887630-aba1-11e7-9d14-6ae26ec97274.PNG)

**Comment by MarkPieszak** [comment]
Yeah those exact ones are from ngx-translate updates Olivier's made.
The TranslateLoader itself requires `HttpClient` as a dependency now, instead of regular `Http`.

All those updates are coming soon, I have the 5.0 branch that'll be merged to master soon with all its updates.

This breaking change above is one of them: https://github.com/MarkPieszak/aspnetcore-angular2-universal/pull/437/files#diff-1c8f345fff94162c0c0a8ae7c14bad47R30
