### ISSUE TITLE
Help with adding Froala editor :)

### ISSUE THREAD

**Issue by digibum** [MarkPieszak/aspnetcore-angular2-universal#439]
Please I need help with getting [Froala Editor](https://www.froala.com/wysiwyg-editor/docs/framework-plugins/angularjs-2-4) to work with this solution.

I get this error: `ERROR TypeError: this._$element.froalaEditor is not a function`

Added this to angular-cli.json:
`  "styles": [
    "./node_modules/froala-editor/css/froala_editor.pkgd.min.css",
    "./node_modules/froala-editor/css/froala_style.min.css",
    "./node_modules/font-awesome/css/font-awesome.css"
  ],
  "scripts": [
    "./node_modules/jquery/dist/jquery.min.js",
    "./node_modules/froala-editor/js/froala_editor.pkgd.min.js"
  ]`

And imported in app.module.ts:
`import { FroalaEditorModule, FroalaViewModule } from 'angular-froala-wysiwyg';`
`imports: [
        ...
        FroalaEditorModule.forRoot(), FroalaViewModule.forRoot()
        ...]`

Thank you all for helping me with this!

**Comment by MarkPieszak** [comment]
Oh the angular-CLI json file is only there for the generators really (at least for now) 😔Apologies!

You're going to want to import those things in the app.browser NgModule making sure to avoid using them on the server.

You might need to do some webpack swapping so the server doesn't bundle them, I haven't used that library just know of it

**Comment by digibum** [comment]
Thank you. But, how to include it in app.module.broswer?
Where do I include css and js files?

**Comment by MarkPieszak** [comment]
If everything is working, that's perfectly fine!
Typically you want to have webpack bundle these things, but since your using CDNs for those, it's just as easy (if not easier) to keep this way :)

Especially since, I'd imagine those files will probably break server bundles (I'd imagine there's a lot of `window` etc in there). I'd stay with this unless you want to experiment in the pain that is webpack swapping :)

Closing for now, glad you got it working!
