### ISSUE TITLE
Invalid target condition in .csproj

### ISSUE THREAD

**Issue by svoychik** [MarkPieszak/aspnetcore-angular2-universal#506]
What is the idea of using condition `And !Exists('wwwroot\dist')` in .csproj ? If I change smth in my code, the source in wwwroot\dist will not change because of this condition.
Also If I execute `dotnet run` after `dotnet publish` I will have a production build in my wwwroot\dist folder.
Maybe it's better to use:
` <Target Name="DebugRunWebpack" BeforeTargets="Build" 
     Condition=" '$(Configuration)' == 'Debug'">`
instead of
` <Target Name="DebugRunWebpack" BeforeTargets="Build" 
     Condition=" '$(Configuration)' == 'Debug' And !Exists('wwwroot\dist')">`
Thanks

**Comment by Adondriel** [comment]
You are ignoring that we have a bunch of build commands in the package.json. If you forcibly want to re-compile your stuff in the wwwroot, you can do many different commands to do this, basically, if you use either:
`npm run build:dev`
or
`npm run build:prod` 
These should both recompile all of the files you are asking for. The reason that is in the csproj, is so 
1. you don't have to restart in order to rebuild
2. so that startup is much faster.
