### ISSUE TITLE
Template bundling SSR and compiler libs in client

### ISSUE THREAD

**Issue by stephenlautier** [MarkPieszak/aspnetcore-angular2-universal#512]
I'm trying around this template (5.x) and trying to integrate it into our project, after I got it to a working state I realized that the `main-client.js` is way bigger (around 720Kb minified). After several of hours of investigating it I noticed that there was the angular compiler included, along with some SSR libs such as `domino`; and the reason they are being included is because of the following import:

```ts
 import { ORIGIN_URL, REQUEST } from "@nguniversal/aspnetcore-engine";.
```

Any import from `"@nguniversal/aspnetcore-engine"` its bundling the rest.

See screenshot.
![2017-12-06 20_06_56-webpack bundle analyzer](https://user-images.githubusercontent.com/3908723/33680693-bc8ce568-dac2-11e7-987f-79c814c47824.png)

**Comment by MarkPieszak** [comment]
Do the same issues exist with the 4.x version? Thanks for pointing these out!
I reverted master back to 4.x, because at the moment Production/AoT is having major issues with AngularCompilerPlugin, and we need to come up with some core fixes there in the angular-cli repo before being able to use it the way we used AoTPlugin before.

**Comment by stephenlautier** [comment]
Not entirely sure with the 4.x to be honest. 
For the time being I got it working with this template and angular 5.x, just no AoT on SSR, all the rest is working.

As for this issue, I'm not importing any `@nguniversal/aspnetcore-engine` as I don't really need anything from it, I thought they were needed in order for the SSR to work, but they are not needed and our apis are separate from the site.

**Comment by nfdevil** [comment]
So on the current 5.x version of this repo, the AOT is broken? Is there a specific issue that I can subscribe to on the Angular repo that causes this?

**Comment by stephenlautier** [comment]
@nfdevil as I had stated (i havent revised this since last dec tho) AoT is enabled for clientside, not for SSR tho

**Comment by nfdevil** [comment]
@stephenlautier and enabling it on SSR will never be possible, or just not for the moment? So it's either SSR or AOT (SEO and first page speed or smaller file size)

**Comment by stephenlautier** [comment]
It was for that moment, now it might be solved, not sure tho havent checked. But I think you didn't understand me fully.

**Server:** with SSR, no AOT
**Client:** with AOT

So you do get both, you just dont get AoT on the SSR itself (so its a bit less faster for the server)

**Comment by nfdevil** [comment]
Indeed, I dont really get it completely. When I Clone the 4.x version of this repo and dotnet publish it, the main.client.js is 1.2mb instead of 1.7mb with the compiler.js in it. So my issue is, this is not working in The Angular 5.x version of this repo, so I was wondering what issue I could follow on either the Angular repo on the Cli repo that causes this Not to work

**Comment by stephenlautier** [comment]
To strip the `compiler.js` (including domino etc... which are technically for server) from the `main-client.js` you need to do what i stated in the first post, if thats what you're trying to achieve.

 e.g. comment out  `import { ORIGIN_URL, REQUEST } from "@nguniversal/aspnetcore-engine";` https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/ClientApp/app/app.module.browser.ts#L6 (and all its usages), if you do that you shouldnt get the compiler in main-client because that library is pulling down the compiler in the client

**Comment by nfdevil** [comment]
Now I understand! Thanks for clarifying. I hope the Angular Universal team will export those 2 InjectionTokens, because I need them for the ngx-translate httploader :)

**Comment by MarkPieszak** [comment]
@stephenlautier @nfdevil 
This has been fixed in the latest pull of the repo, and issues over in `@nguniversal/aspnet-core-engine` as well, thanks to @CaerusKaru via dfa802628d895cfbff61ccfb5c4556e50860fb42

Make sure you're importing from /tokens at the end

```ts
import { ORIGIN_URL, REQUEST } from "@nguniversal/aspnetcore-engine/tokens";
```

Also get the latest beta.8 of nguniversal aspnetcore and common :+1:

That should fix the issue :)

**Comment by charedim** [comment]
Hi!!, Can I get environment variables from the server without using .NET server side??

**Comment by charedim** [comment]
Hi!!, Can I get environment variables from the server without using .NET server side?

**Comment by charedim** [comment]
Hi!!, Can I get environment variables from the server without using .NET server side?
