### ISSUE TITLE
More Lazy Loading... vendor.sj 4MB+ main-client.js 4MB+ :|

### ISSUE THREAD

**Issue by electricessence** [MarkPieszak/aspnetcore-angular2-universal#517]
It would be nice to see more granular HTTP2 friendly lazy loading of assets.  It seems ridiculous to load 8MB+ up front. :(

**Comment by MarkPieszak** [comment]
This is happening in Production mode with Gzip etc?

**Comment by electricessence** [comment]
If so, I don't think it's a good idea to diverge so far from what happens in production from what happens in dev.  What is the benefit of bundling these files so tightly?

When I say 'granular' I mean so that lazy loading can occur organically and not be concerned with how the bundle is configured on any given day.

**Comment by electricessence** [comment]
This may go against other opinions, but I can assure you there are a large group of developers that would be very concerned with: "if tomorrow I introduce a new module as part of my code, then the entire vendor.js is invalidated."

**Comment by electricessence** [comment]
Ok so I've been looking more into this and it may be my lack of understanding because all-in-all this is very complicated for a single individual to grasp in its entirety.  It looks like when compiled to a single bundle, angular (5) is less than 850K.  When referenced minified versions (umd.min in node_modules/@angular), it's about 1.2MB.

I'm starting to grasp the priorities of how this repo is designed.  But I think some additional readme about how/why the webpack config is the way it is would be helpful for people like me to not get hung up on how files are bundled/deployed.

**Comment by MarkPieszak** [comment]
I'll try to get some more information in there!
It is quite a lot, it can definitely take quite a while to really figure out how it all plays together, I was trying to save people a bit of time so they could focus on just tweaking it to meet their needs instead of wiring it all up :)

Dev is always different (and larger) mainly because of all the sourcemaps / compiler / not being minified / etc. We need all that good stuff for debugging in Chrome devtools 👍 

The webpack config is really just creating 2 separate bundles, one for Client, one for Server. The server one is what is being invoked in a Node process to do the server-side rendering, the other is your typical Angular SPA.

Hope that helps!
