### ISSUE TITLE
Problem with jQuery plugin-themepunch revolution slider

### ISSUE THREAD

**Issue by GetTaxSolutions** [MarkPieszak/aspnetcore-angular2-universal#528]
Hello,
I added jQuery into the webpack and try to add jQuery slider plugin. It looks that is working and have no error in the console but actually this made problems with others jQuery plugins in my site. After some investigating I found that have two duplicated 'app-root' elements into the DOM. One of them is hidden but is the reason to crash other plugins. What can be the reason to have these duplicated elements? How I can investigate and fix this issue?
![image](https://user-images.githubusercontent.com/32810729/34468575-89eab35e-ef14-11e7-9abe-82b1e1456fb7.png)

I have example fork with my implementation here:
[https://github.com/GetTaxSolutions/aspnetcore-angular2-universal/commit/f3376d9b5cc798a07809dd386117b8ede4080229](https://github.com/GetTaxSolutions/aspnetcore-angular2-universal/commit/f3376d9b5cc798a07809dd386117b8ede4080229)

**Comment by MarkPieszak** [comment]
Are there any errors coming up in the console?
My guess is during preboot it may of failed due to some errors in the code somewhere, but I can't be certain.

**Comment by GetTaxSolutions** [comment]
No errors in the console. You can see into the fork. I don't know what can be the reason and can't catch the point to debug where is the problem. If add the same HTML/CSS/scripts in separate isolated project without Angular it's working fine. Also it's ok in Angular 1.x (old project which we have implemented and now trying to migrate to Angular 5.x).

**Comment by Adondriel** [comment]
Ah, don't try to migrate to 5 yet, as it seems angular really hates SSR or something. The ng5 branch is still in heavy beta, atm and We are also still waiting for https://github.com/angular/angular-cli/pull/8951 to be done for ng5 support. It's best to stick with ng4.x for now.

**Comment by MarkPieszak** [comment]
@GetTaxSolutions 
Make sure you're wrapping anything that uses jQuery with tons of isBrowsers, and also that jQuery is included via a CDN or only being included for the Client bundle. (By being included only in main.browser file)

Moving these (might) help, but it could be quite a number of things causing the problem in the way it's all configured. I don't have the time to debug it unfortunately :(
```ts
import '../../ClientApp/jquery.plugins/jquery.themepunch.plugins.min.js';
import '../../ClientApp/jquery.plugins/jquery.themepunch.revolution.min.js';
```

As Adam was saying, version 5 might be at fault since it won't be ready until that PR gets merged and published up to ngtools/webpack.
