### ISSUE TITLE
[bug] sln cannot be opened in vs2017RC (xproj)

### ISSUE THREAD

**Issue by vip32** [MarkPieszak/aspnetcore-angular2-universal#54]
after the suggested upgrading this is shown:

Angular2Spa.xproj: Failed to migrate XProj project Angular2Spa. 'dotnet migrate --skip-backup -s -p "C:\Dropbox\projects\_github\aspnetcore-angular2-universal" -x "C:\Dropbox\projects\_github\aspnetcore-angular2-universal\Angular2Spa.xproj"' exited with error code 1.
Angular2Spa.xproj: No executable found matching command "dotnet-migrate"

also the project.json/xproj has to be migrated to the new csproj structure.

**Comment by MarkPieszak** [comment]
Unfortunately the aspnet migrate tool has some issues and doesn't work just yet, I can't find the issue on github at the moment. I've ran into the same problem with any project I've tried upgrading.

I thought it might be best to wait before having the project ready for vs2017 since it hasn't been officially released just yet. 
I'll try and post the necessary files needed for it to open in 2017 in here.

Wish there was a way to have it open/work in both 😓
