### ISSUE TITLE
Changes in Angular Application Source files(HTML) are not reflecting 

### ISSUE THREAD

**Issue by MalateshPatil** [MarkPieszak/aspnetcore-angular2-universal#558]
Node.js - 6.10.2
npm - 3.10.10
 .NET Core Runtime 2.0.0
.NET Core SDK 2.0.0

Above are my local versions of set of requirements.

I tried to run the solution in VS Code with below commands
```
1. npm install && npm run build:dev && dotnet restore
2. dotnet run
```
Then application is running fine.

But If I made any changes in HTML files , changes are not reflecting even after page reload.  I am getting console error as **"08c7562b228467efa302.hot-update.json"** Not Found.  Please anybody suggest.

Also I have another question - Can we use Angular Material and Kendo UI Components with this solution . If possible, please attach any useful links.

**Comment by MarkPieszak** [comment]
There's some info here in the docs, you need to make sure you're setting the ASPNETCORE_ENVIRONMENT=Development

https://github.com/MarkPieszak/aspnetcore-angular2-universal#visual-studio-code

```bash
# on Windows:
set ASPNETCORE_ENVIRONMENT=Development
# on Mac/Linux
export ASPNETCORE_ENVIRONMENT=Development 
```

Also as a sidenote, make sure you update your Node, 6.10 has long been deprecated. You want to use the latest 8.x or 9.x versions, otherwise you might run into other funky issues!

Good luck!

**Comment by peterdobson** [comment]
FYI, I had an issue with azure websites and Node 9x. As far as I understand as of today (22nd May 2018) the latest version node supported in azure websites is 8.9.4
