### ISSUE TITLE
Problem With localize-router !

### ISSUE THREAD

**Issue by MR-MAP** [MarkPieszak/aspnetcore-angular2-universal#563]
When Add 'localize-router' project Error To 'Cannot instantiate cyclic dependency'

this Is Same :
https://github.com/Greentube/localize-router/issues/99

**Comment by MarkPieszak** [comment]
It looks like it's an internal problem with localize-router (https://github.com/Greentube/localize-router/issues/99#issuecomment-357307317), although I'm not familiar with that Library. But however it's being used, it should be grabbing the dependency that's causing this error via the `Injector` and not through normal D.I. within the constructor. This is causing a circular dep issue with the Injector itself since it most likely hasn't been initialized (or is initializing in a circle).

You might need to fork it and apply the fix mentioned in that comment to see if you can get it working! Hope that helps
