### ISSUE TITLE
how to run AOT build?

### ISSUE THREAD

**Issue by nfdevil** [MarkPieszak/aspnetcore-angular2-universal#564]
I've tried dotnet publish -c Release and npm build:prod on a fresh clone of the repo where I've enabled the line 
`new BundleAnalyzerPlugin(),`
in my webpack config, but the compiler is still included:

![image](https://user-images.githubusercontent.com/7434048/36949894-795d465e-1fee-11e8-8c66-7760cef4d9af.png)

How can I get the AOT working?

**Comment by stephenlautier** [comment]
Seems duplicate as my issue https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/512 - also theres a solution

**Comment by MarkPieszak** [comment]
Closing as duplicate & fixed :+1:

---

This has been fixed in the latest pull of the repo, and issues over in @nguniversal/aspnet-core-engine as well, thanks to @CaerusKaru via dfa8026

Make sure you're importing from /tokens at the end

import { ORIGIN_URL, REQUEST } from "@nguniversal/aspnetcore-engine/tokens";
Also get the latest beta.8 of nguniversal aspnetcore and common 👍

That should fix the issue :)
