### ISSUE TITLE
How to configure Angular SEO

### ISSUE THREAD

**Issue by albrookesplowman** [MarkPieszak/aspnetcore-angular2-universal#602]
Hi,

I have started using this template and it is working really well.  I have a published website but I am just wondering how to configure the SEO data so that it will be found in google search etc.. 

I have found some places in the code that refer to meta data but where is the correct place to put the information e.g. author, page key words, page description etc...

Many thanks for the help

Alan

**Comment by peterdobson** [comment]
Within the setMetaAndLinks(event) method in app.component.ts you can update the meta tags e.g.

      this.meta.updateTag({ name: 'description', content: title });
      this.meta.updateTag({ name: 'keywords', content: 'word1, word2, word3' });
      this.meta.updateTag({ name: 'fb:app_id', content: '123456789012345' })
      this.meta.updateTag({ name: 'og:type', content: 'article' });

etc

**Comment by MarkPieszak** [comment]
Thank you @peterdobson :+1:

Yes, you can use the meta service to handle updating anything, either specifically from a Component, or you can store all the data within the routing `data{}`, and the app.component will handle it when that specific route is hit automatically.

https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/ClientApp/app/app.module.ts#L81-L86

Here it injects the data{} from routes automatically during route change events.
https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/ClientApp/app/app.component.ts#L77

I typically use a mix of the two, since sometimes it's not a specific "route" that needs to update it.

Hope that helps! :+1:
