### ISSUE TITLE
Angular 6?

### ISSUE THREAD

**Issue by LiverpoolOwen** [MarkPieszak/aspnetcore-angular2-universal#619]
Do we have any know blockers on upgrading to Angular version 6? 
I see we need to use Node version 8, will this be an issue for deployments?

If not I could set up a pull request.

**Comment by JacobSiegle** [comment]
Blocker - 
https://github.com/angular/preboot/issues/85

**Comment by MarkPieszak** [comment]
We'd need to run the rxjs-5-to-6 migrate script, make sure all the imports are updated and usage switched to pipeable operators and such. Otherwise I don't know how long it'd take - I was hoping to get to it in the next week if I have a free full day

**Comment by wmild** [comment]
If you use rxjs-compat, then you can delay the pipe migration stuff.  For me, the tricky part seems to be getting webpack 4 to work, because I need to figure out how to set the mode to production/development in the webpack.config.js.

**Comment by OceansideBill** [comment]
I just submitted a pr related to RXJS 6.  For those who are maintaining a site based on this repo, the instructions at: https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md are useful, the linting tool works great and is the basis for most of the pr.  

Found an issue however that turned out to be related to the translation libraries.  Was getting a good build but failing to run until I upgraded those references to final builds that supported ng5.  Along the way made some other package updates that I've been using including an upgrade to ngx-bootstrap which required an app-module change.  Hope this helps.

**Comment by Adondriel** [comment]
I thought we removed the translation stuff awhile ago? Personally, I
dislike that we have that, as it adds yet another thing I have to remove
anytime I start a new project. I suppose some people do use it, but it
would be nice if we had a branch dedicated to having a completely blank
slate, with nothing but a basic bootstrap template(with a horizontal nav,
as the vertical one is ugly, imo) Also, have we not updated to BS4 yet,
either? If not, I'll make a PR for that as well.

**Comment by OceansideBill** [comment]
BS 4.1.1 is in the PR I submitted.  Only required a minor change to app.module to support the accordionModule import.

**Comment by RZeni** [comment]
# #626 Updated

**Comment by MarkPieszak** [comment]
We have the latest and greatest 6.0 thanks to @RZeni 👍👍
Everyone take it for a spin, so far everything looks great here!
