### ISSUE TITLE
msbuild argument is missing on init

### ISSUE THREAD

**Issue by DonCorleone** [MarkPieszak/aspnetcore-angular2-universal#658]
Hello Mark

Thank you so much for this really great and huge starter! 🥇 Its an amazing bundle of technologies i'm interested in. 

I had a little issue after calling `npm install && npm run build:dev && dotnet restore`
 on my mac in the macOS-Terminal:

`MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.`

its because of the docker project i think..

so i did a manual `dotnet restore Asp2017.csproj` > that worked fine!

After calling the _[Development] Debug TypeScript_ - Launch via F5 in Visual Studio Code, the same message appeared in my Console Log. So edited task.json - it looks now like this:

`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "dotnet",
    "isShellCommand": true,
    "args": [],
    "tasks": [
        {
            "taskName": "build",
            "args": ["ASP2017.csproj"],
            "isBuildCommand": true,
            "showOutput": "silent",
            "problemMatcher": "$msCompile"
        }
    ]
}`

Everything is working fine now!

is this correct? would you do it in another way? 

Thank you so much! 👍 👍 👍 

Greetings - Linus

**Comment by GRIMMR3AP3R** [comment]
No, you are correct this is the way it should be built. The solution file was recently added to the project which seems to be confusing the .net build command. You can also do 'dotnet restore Asp2017.sln' and it will build all the projects within the solution instead of just the project and its dependencies.

**Comment by MarkPieszak** [comment]
It looks like @kloned found the fix for this one via https://github.com/MarkPieszak/aspnetcore-angular2-universal/commit/9071694afc5f3b9a2c4c7219d36a3ff65328e839

Adding that `"args": ["Asp2017.sln"],` in the tasks.json file does the trick! 👍 
@DonCorleone 

I appreciate the kind words as well! It's been a team project, I'm glad the starter is helping so many :)

**Comment by enriquehernandez** [comment]
Hello Mark,

I have the same problem:
MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.

**Comment by mleader1** [comment]
@enriquehernandez  move docker files such as docker-compose.dcproj to another folder will do the trick
