### ISSUE TITLE
Question about mdbootstrap

### ISSUE THREAD

**Issue by MilanKozomora** [MarkPieszak/aspnetcore-angular2-universal#678]
I am beginner in Angular and webpack. Can anyone help me integrate mdbootstrap in this starter. Here is a link to their instructions https://mdbootstrap.com/angular/angular-universal/. 
Where to put "domino", and what to do without index.html.
Where to put whitelist. , etc..

**Comment by CybrZr00** [comment]
You can put external scripts and css links in Views > Shared > _Layout.cshtml or for css you can import the sheets via app.component.css, although you will have to be sure you change the extension to .scss for md bootstrap, if I remember correctly there are some issues with paths when it comes to md-bootstrap so you may find you need to change the variables.  One thing I will say about md-bootstrap is that with a little digging you can make all of their components yourself quite easily, I recently did this because I no longer wanted to rely on Bootstrap at all. The only time I had issues was with tooltips and popovers because they need quite a bit of code to be reusable. If you go that root remeber to avoid direct DOM manipulaton and use Renderer2. Another excellent option is angular-material, there are plenty of guides on how to use / cusotomise it and it now works with universal.

**Comment by MilanKozomora** [comment]
Thank you for your hep. I appreciate it.

**Comment by MarkPieszak** [comment]
Thanks for helping out with this one Cybr!
