### ISSUE TITLE
start:dashboard not serving

### ISSUE THREAD

**Issue by daveo1001** [MarkPieszak/aspnetcore-angular2-universal#89]
fresh clone.
npm install && dotnet restore - no errors.
npm run start:dashboard - no errors.

Project is running at http://localhost:8080/
webpack output is served from /dist/
webpack webpacks without errors.

http://localhost:8080/ can't be found.

the /dist/ folder contains the following:
0.js
0.js.map
main-client.js
main-client.js.map
vendor.css
vendor.js
vendor-manifest.json

this seems... lacking.
Know what I'm doing wrong?

Side note, server serves when I launch IIS from VS. Is that how I'm supposed to do things?

**Comment by EmaGht** [comment]
Might be wrong but this project is based on ASP.NET MVC so you NEED ASP.NET to take care of your Index.cshtml which can be done only by starting it with dotnet. If you start it with npm it shouldn't work

**Comment by MarkPieszak** [comment]
@daveo1001 That may be my fault, the dashboard was working a bit ago, but there have been some underlying build changes I might of forgotten to check/test that functionality! Thanks for letting me know I'll look into it right now.

As for Launching, yes IIS. So basically it's bare-bones MVC as Ema was saying. This allows us to serialize the Angular application on the server, since we're able to invoke a Node process inside of .NET Core (universal is written in Node), giving you an almost instant application paint. You can test it by "disabling JavaScript" in Chrome settings and refreshing. That's all server rendered.

Let me get back to you about the dashboard!

**Comment by daveo1001** [comment]
@EmaGht @MarkPieszak Thanks folks! Makes sense!

**Comment by MarkPieszak** [comment]
We're all set, you can see the updates in commit https://github.com/MarkPieszak/aspnetcore-angular2-universal/commit/a81495821c37b5451485a02a00d46ffac0f2a94a or can get latest to see that it works now :)

![image](https://cloud.githubusercontent.com/assets/2574412/22744066/38baba28-edea-11e6-84eb-c94835ac8574.png)

**Comment by MarkPieszak** [comment]
Had to temporarily shut off the dashboard to fix the npm install from hanging, so i'll re-open this until I can get them both to play well together.

Related dashboard issue: 
https://github.com/FormidableLabs/webpack-dashboard/issues/96

**Comment by MarkPieszak** [comment]
This has been removed for now, I might look into re-adding the dashboard in the future.

For now it caused so much headache before I'm afraid to even try again :cry: 
We'll see though, trying to knock out the bigger fish at the moment!
